### ISSUE TITLE
Peer to Peer code review 

### ISSUE THREAD

**Issue by Oscah01** [OmarMWarraich/Html-Js-Capstone#3]
Please add the dotted background image as it is shown in the original design on each card of the speakers' section.
Your join summit button is not properly aligned, please fix it by giving equal margins on all sides. 
Please add hover to your menu links.

**Comment by OmarMWarraich** [comment]
@Oscah01 Please note that all the above mentioned discrepancies have been resolved, therefore, this issue is being closed.
